project:
  type: website
  render:
    - index.md
    - about.md
    - articles/**/*.{md,ipynb}
    - resources/**/*.{md,ipynb}
  resources:
    - assets/**            # ensure local fonts, icons, images are copied
    - resources/**         # optional: keep downloads/attachments

website:
  title: "Syntax & Empathy"
  site-url: "https://syntax-and-empathy.github.io/s-and-e-hub"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: articles/
        text: Articles
      - href: resources/
        text: Resources
      - href: about.md
        text: About
  search: true
  page-footer:
    center: |
      © 2025 Syntax & Empathy — [Licensed under CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: true
    smooth-scroll: true
    code-copy: true
    anchor-sections: true

execute:
  freeze: auto
